import turtle
turtle.shape("turtle") 
turtle.color("Purple")
turtle.forward (50)
turtle.right (90)
turtle.forward (50)
turtle.right (90)
turtle.forward (50)
turtle.right (90)
turtle.forward (50)
turtle.right (90)
turtle.left (90)
turtle.up() 
turtle.forward (100)
turtle.down()
turtle.color("Red")
turtle.right (90)
turtle.forward (50)
turtle.right (90)
turtle.forward (50)
turtle.right (90)
turtle.forward (50)
turtle.right (90)
turtle.left (90)
turtle.right (90)
turtle.forward (50)
turtle.exitonclick()